// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KP_Soloviev.Models;

public partial class Anime_Rating
{
    public int AnimeID { get; set; }

    public int RatingID { get; set; }

    public virtual Anime Anime { get; set; }

    public virtual Rating Rating { get; set; }
}