// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KP_Soloviev.Models;

public partial class Anime_Favourite
{
    public int AnimeID { get; set; }

    public int FavouriteID { get; set; }

    public virtual Anime Anime { get; set; }

    public virtual Favourite Favourite { get; set; }
}