// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KP_Soloviev.Models;

public partial class Anime
{
    public int AnimeID { get; set; }

    public string Title { get; set; }

    public byte[] Photo { get; set; }

    public string Genre { get; set; }

    public int AgeRating { get; set; }

    public int Duration { get; set; }

    public int Series { get; set; }

    public int Seasons { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Anime_Favourite> Anime_Favourites { get; set; } = new List<Anime_Favourite>();

    public virtual ICollection<Anime_Rating> Anime_Ratings { get; set; } = new List<Anime_Rating>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}