// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KP_Soloviev.Models;

public partial class Favourite
{
    public int FavouriteID { get; set; }

    public string NameOfList { get; set; }

    public DateOnly CreationDate { get; set; }

    public int UserID { get; set; }

    public virtual ICollection<Anime_Favourite> Anime_Favourites { get; set; } = new List<Anime_Favourite>();

    public virtual User User { get; set; }
}