// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KP_Soloviev.Models;

public partial class Review
{
    public int ReviewID { get; set; }

    public string Title { get; set; }

    public string Text { get; set; }

    public int AnimeID { get; set; }

    public DateOnly Date { get; set; }

    public string Author { get; set; }

    public int UserID { get; set; }

    public virtual Anime Anime { get; set; }

    public virtual User User { get; set; }
}